### ISSUE TITLE
Modem with +CSIM support

### ISSUE THREAD

**Issue by mitshell** [fasferraz/USIM-https-server#1]
Dear Fabricio,

Thanks for publishing this project. Would you have any reference of 4G modems, which support the AT+CSIM command ?
Thanks in advance,
Benoit Michau

**Comment by fasferraz** [comment]
Hi Benoit,
No I don't, and according to 3gpp 27.007 the implementation of this command is optional, so you probably need to check every model documentation to get this information...

I have three modems/modules that support it: 
- An old ZTE MF622 (and it may be dependent on the firmware. I once upgrade it, and lost this AT command, so I had to revert the upgrade)
-  Quectel BG96 and Quectel EC20

**Comment by mitshell** [comment]
Thanks for your quick feedback !
